version: "3.9"

services:
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/app
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=caeli512
      - MAIL_USERNAME= erick.founders@gmail.com
      - MAIL_PASSWORD= wgzpczwwngodvusg
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: caeli512
      POSTGRES_DB: app